resolver: lts-7.13

# For production we need to build the executable in an ephemeral Docker image,
# otherwise it will have the executable file format of the local architecture,
# that is, if you build on a Mac, the executable will have Mach-O format which
# can not be used in the production Docker container (which is Linux based).
docker:
  enable: true
  auto-pull: true
  stack-exe: /Users/bastian/projekte/elm-lang-de/docker/stack-binary/stack-1.3.2-linux-x86_64-static/stack
system-ghc: true

# For development:
# system-ghc: false

packages:
- '.'

flags: {}

# elm-lang-de Docker Image
image:
  container:
    base: fpco/stack-run
    name: basti1302/elmlangde-app
    add:
      backend: /elmlangde/backend
      dist: /elmlangde/dist

extra-package-dbs: []

extra-deps:
- HDBC-postgresql-2.3.2.4
- HsSyck-0.53
- dbmigrations-2.0.0
- http-api-data-0.3.3
- servant-0.9.1.1
- servant-client-0.9.1.1
- servant-server-0.9.1.1
- uuid-aeson-0.1.0.0
- yaml-light-0.1.4
